name: CI/CD to GHCR

on: [push]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/sharkweb1/spring-boot-k8s:latest .
          docker tag ghcr.io/sharkweb1/spring-boot-k8s:latest ghcr.io/sharkweb1/spring-boot-k8s:${{ github.sha }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: sharkweb1
          password: ${{ secrets.SPRIN_APP }}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/sharkweb1/spring-boot-k8s:latest
          docker push ghcr.io/sharkweb1/spring-boot-k8s:${{ github.sha }}
